/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Series
         * @description The one list endpoint behind every grid (library, favorites, gallery, …).
         */
        get: operations["list_series_api_series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/series/{series_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Series
         * @description Full series detail.
         */
        get: operations["get_series_api_series__series_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/series/{series_id}/chapters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Chapters
         * @description Chapters grouped by volume (Related/chapters tab).
         */
        get: operations["list_chapters_api_series__series_id__chapters_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{chapter_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Chapter
         * @description Chapter detail for the reader.
         */
        get: operations["get_chapter_api_chapters__chapter_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Updates
         * @description Recently updated chapters across the library.
         */
        get: operations["updates_api_updates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/updates/unread": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Unread Updates
         * @description Unread chapters across the library.
         */
        get: operations["unread_updates_api_updates_unread_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard
         * @description One call for the Home dashboard: stats + continue-reading + updates + added.
         */
        get: operations["dashboard_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/libraries/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Libraries Summary
         * @description Per-library storage usage (Home strip + About).
         */
        get: operations["libraries_summary_api_libraries_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search
         * @description Title search powering the navbar.
         */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/series/{series_id}/related": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Related
         * @description Other series of the same kind (Related tab).
         */
        get: operations["related_api_series__series_id__related_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/series/{series_id}/art": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Series Art
         * @description Extra art for a series (Art tab).
         */
        get: operations["series_art_api_series__series_id__art_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/series/{series_id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gallery Images
         * @description Cursor-paginated gallery image URLs (GalleryDetail grid + Lightbox).
         */
        get: operations["gallery_images_api_series__series_id__images_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/series/{series_id}/cover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Series Cover
         * @description AVIF cover thumbnail (size = cover | detail).
         */
        get: operations["series_cover_api_series__series_id__cover_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/series/{series_id}/images/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Gallery Image
         * @description A single gallery image (AVIF or original bytes).
         */
        get: operations["gallery_image_api_series__series_id__images__index__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chapters/{chapter_id}/pages/{n}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Chapter Page
         * @description A single chapter page (1-based); ETag + Cache-Control + 304.
         */
        get: operations["chapter_page_api_chapters__chapter_id__pages__n__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChapterDetailOut */
        ChapterDetailOut: {
            /** Id */
            id: string;
            /** Seriesid */
            seriesId: string;
            /** Volume */
            volume: number | null;
            /** Number */
            number: string;
            /** Title */
            title?: string | null;
            /** Group */
            group?: string | null;
            /** Language */
            language: string;
            /** Pagecount */
            pageCount: number;
            /** Comments */
            comments: number;
            /** Read */
            read: boolean;
            /** Uploadedat */
            uploadedAt?: string | null;
        };
        /** ChapterOut */
        ChapterOut: {
            /** Id */
            id: string;
            /** Volume */
            volume: number | null;
            /** Number */
            number: string;
            /** Title */
            title?: string | null;
            /** Group */
            group?: string | null;
            /** Language */
            language: string;
            /** Uploadedat */
            uploadedAt?: string | null;
            /** Read */
            read: boolean;
            /** Comments */
            comments: number;
        };
        /** DashboardOut */
        DashboardOut: {
            stats: components["schemas"]["DashboardStats"];
            /** Continuereading */
            continueReading: components["schemas"]["SeriesOut"][];
            /** Recentupdates */
            recentUpdates: components["schemas"]["RecentUpdateOut"][];
            /** Recentlyadded */
            recentlyAdded: components["schemas"]["SeriesOut"][];
        };
        /** DashboardStats */
        DashboardStats: {
            /** Series */
            series: number;
            /** Unreadchapters */
            unreadChapters: number;
            /** Reading */
            reading: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LibrarySummaryOut */
        LibrarySummaryOut: {
            /** Key */
            key: string;
            /** Title */
            title: string;
            /** Sizegb */
            sizeGb: number;
        };
        /** Page[RecentUpdateOut] */
        Page_RecentUpdateOut_: {
            /** Items */
            items: components["schemas"]["RecentUpdateOut"][];
            /** Nextcursor */
            nextCursor?: string | null;
        };
        /** Page[SeriesOut] */
        Page_SeriesOut_: {
            /** Items */
            items: components["schemas"]["SeriesOut"][];
            /** Nextcursor */
            nextCursor?: string | null;
        };
        /** Page[str] */
        Page_str_: {
            /** Items */
            items: string[];
            /** Nextcursor */
            nextCursor?: string | null;
        };
        /** RecentUpdateOut */
        RecentUpdateOut: {
            series: components["schemas"]["SeriesOut"];
            /** Volume */
            volume: number | null;
            /** Chapter */
            chapter: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** SeriesArtOut */
        SeriesArtOut: {
            /** Images */
            images: string[];
        };
        /** SeriesOut */
        SeriesOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Coverurl */
            coverUrl: string;
            /** Authors */
            authors: string[];
            /** Artists */
            artists: string[];
            /** Status */
            status: string;
            /** Contentrating */
            contentRating: string;
            /** Demographic */
            demographic: string;
            /** Tags */
            tags: components["schemas"]["TagOut"][];
            /** Chaptercount */
            chapterCount: number;
            /** Unreadcount */
            unreadCount: number;
            /** Year */
            year?: number | null;
            /** Description */
            description?: string | null;
            /** Lastreadchapter */
            lastReadChapter?: number | null;
            /** Totalchapters */
            totalChapters?: number | null;
            /** Origincountry */
            originCountry?: string | null;
            /** Rating */
            rating?: number | null;
            /**
             * Favorite
             * @default false
             */
            favorite: boolean;
            /** Kind */
            kind?: string | null;
            /** Imagecount */
            imageCount?: number | null;
            /** Source */
            source?: string | null;
            /** Characters */
            characters?: string[] | null;
            /** Librarystatus */
            libraryStatus?: string | null;
        };
        /** TagOut */
        TagOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Group */
            group: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VolumeGroupOut */
        VolumeGroupOut: {
            /** Volume */
            volume: number | null;
            /** Chapters */
            chapters: components["schemas"]["ChapterOut"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_series_api_series_get: {
        parameters: {
            query?: {
                kind?: string | null;
                shelf?: string | null;
                favorite?: boolean | null;
                q?: string | null;
                tags?: string | null;
                tagMode?: string;
                ratings?: string | null;
                demographics?: string | null;
                pubStatus?: string | null;
                readState?: string | null;
                artist?: string | null;
                source?: string | null;
                sort?: string;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SeriesOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_series_api_series__series_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_chapters_api_series__series_id__chapters_get: {
        parameters: {
            query?: {
                language?: string | null;
                order?: string;
            };
            header?: never;
            path: {
                series_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VolumeGroupOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chapter_api_chapters__chapter_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapter_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChapterDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updates_api_updates_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RecentUpdateOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unread_updates_api_updates_unread_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RecentUpdateOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_api_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOut"];
                };
            };
        };
    };
    libraries_summary_api_libraries_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibrarySummaryOut"][];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query?: {
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    related_api_series__series_id__related_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    series_art_api_series__series_id__art_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeriesArtOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gallery_images_api_series__series_id__images_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                series_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_str_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    series_cover_api_series__series_id__cover_get: {
        parameters: {
            query?: {
                size?: string;
            };
            header?: never;
            path: {
                series_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    gallery_image_api_series__series_id__images__index__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: string;
                index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chapter_page_api_chapters__chapter_id__pages__n__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chapter_id: string;
                n: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
