"""add import pattern presets

Revision ID: 2b7bd54c33a3
Revises: a1f25b5d61c5
Create Date: 2026-07-25 22:04:37.591454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b7bd54c33a3'
down_revision = 'a1f25b5d61c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pattern_presets', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_config', schema=None) as batch_op:
        batch_op.drop_column('pattern_presets')

    # ### end Alembic commands ###
