"""import_config singleton

Revision ID: 2f54a96b80db
Revises: b6cabeb7578d
Create Date: 2026-07-25 13:57:29.669249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f54a96b80db'
down_revision = 'b6cabeb7578d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_config',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=False),
    sa.Column('filename_pattern', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_config')
    # ### end Alembic commands ###
