"""provider oauth account

Revision ID: 37829eecb1cb
Revises: c32e0a9dead7
Create Date: 2026-07-25 07:26:16.200375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37829eecb1cb'
down_revision = 'c32e0a9dead7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('client_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('client_secret_enc', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('refresh_token_enc', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider', schema=None) as batch_op:
        batch_op.drop_column('refresh_token_enc')
        batch_op.drop_column('client_secret_enc')
        batch_op.drop_column('client_id')
        batch_op.drop_column('account_name')

    # ### end Alembic commands ###
