"""cascade-delete download tasks with their series

Revision ID: 44d2dfce9ddb
Revises: 6bd8f0e2bb90
Create Date: 2026-07-27 12:20:32.298628

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "44d2dfce9ddb"
down_revision = "6bd8f0e2bb90"
branch_labels = None
depends_on = None


# SQLite FKs are unnamed on this table (no naming_convention configured on Base.metadata),
# so batch mode can't `drop_constraint(None, ...)` — give the reflected FK a synthetic name
# via this convention so it can be dropped and recreated with the new ON DELETE action.
_FK_NAMING_CONVENTION = {"fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s"}
_FK_NAME = "fk_download_task_series_id_series"


def upgrade() -> None:
    # Rows already orphaned by the old ON DELETE SET NULL (invisible + un-deletable via
    # the API, since DownloadTaskOut.series is required) can't survive the new NOT NULL.
    op.execute(sa.text("DELETE FROM download_task WHERE series_id IS NULL"))
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "download_task", schema=None, naming_convention=_FK_NAMING_CONVENTION
    ) as batch_op:
        batch_op.alter_column("series_id", existing_type=sa.VARCHAR(length=12), nullable=False)
        batch_op.drop_constraint(_FK_NAME, type_="foreignkey")
        batch_op.create_foreign_key(_FK_NAME, "series", ["series_id"], ["id"], ondelete="CASCADE")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "download_task", schema=None, naming_convention=_FK_NAMING_CONVENTION
    ) as batch_op:
        batch_op.drop_constraint(_FK_NAME, type_="foreignkey")
        batch_op.create_foreign_key(_FK_NAME, "series", ["series_id"], ["id"], ondelete="SET NULL")
        batch_op.alter_column("series_id", existing_type=sa.VARCHAR(length=12), nullable=True)

    # ### end Alembic commands ###
