"""download_task provider and remote_json

Revision ID: 7cb0d1378b76
Revises: 999d293951de
Create Date: 2026-07-25 12:39:47.992431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cb0d1378b76'
down_revision = '999d293951de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('remote_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_task', schema=None) as batch_op:
        batch_op.drop_column('remote_json')
        batch_op.drop_column('provider')

    # ### end Alembic commands ###
