"""tracker pkce verifier

Revision ID: 999d293951de
Revises: a4538373142a
Create Date: 2026-07-25 08:17:34.746179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '999d293951de'
down_revision = 'a4538373142a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pkce_verifier', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracker', schema=None) as batch_op:
        batch_op.drop_column('pkce_verifier')

    # ### end Alembic commands ###
