"""book restore_progress_json

Revision ID: a1f25b5d61c5
Revises: 2f54a96b80db
Create Date: 2026-07-25 15:39:40.085842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1f25b5d61c5'
down_revision = '2f54a96b80db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restore_progress_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('restore_progress_json')

    # ### end Alembic commands ###
