"""series available_chapters

Revision ID: a3685077bbd1
Revises: 37829eecb1cb
Create Date: 2026-07-25 07:35:39.489381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3685077bbd1'
down_revision = '37829eecb1cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('available_chapters', sa.Integer(), nullable=False, server_default='0')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_column('available_chapters')

    # ### end Alembic commands ###
