"""tracker oauth columns

Revision ID: a4538373142a
Revises: a3685077bbd1
Create Date: 2026-07-25 08:02:26.451724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4538373142a'
down_revision = 'a3685077bbd1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('client_secret_enc', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('access_token_enc', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('refresh_token_enc', sa.Text(), nullable=True))
        batch_op.drop_column('refresh_token')
        batch_op.drop_column('access_token')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_token', sa.VARCHAR(length=2048), nullable=True))
        batch_op.add_column(sa.Column('refresh_token', sa.VARCHAR(length=2048), nullable=True))
        batch_op.drop_column('refresh_token_enc')
        batch_op.drop_column('access_token_enc')
        batch_op.drop_column('client_secret_enc')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###
