"""add lychee.info sidecar hash and version to series

Revision ID: aeaeff445c44
Revises: da574a33f5a8
Create Date: 2026-07-28 03:02:01.605330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeaeff445c44'
down_revision = 'da574a33f5a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('metadata_file_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('metadata_file_version', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_column('metadata_file_version')
        batch_op.drop_column('metadata_file_hash')

    # ### end Alembic commands ###
