"""add collection provider linkage

Revision ID: bac440c50fd8
Revises: 2b7bd54c33a3
Create Date: 2026-07-25 23:09:15.013553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bac440c50fd8'
down_revision = '2b7bd54c33a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('provider_list_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_collection_provider_list_id'), ['provider_list_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_provider_list_id'))
        batch_op.drop_column('provider_list_id')
        batch_op.drop_column('provider')

    # ### end Alembic commands ###
