"""provider data_saver

Revision ID: c32e0a9dead7
Revises: d59ac262ce53
Create Date: 2026-07-25 07:05:05.258996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c32e0a9dead7'
down_revision = 'd59ac262ce53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider', schema=None) as batch_op:
        # server_default backfills existing provider rows; the ORM default drives new ones.
        batch_op.add_column(
            sa.Column('data_saver', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider', schema=None) as batch_op:
        batch_op.drop_column('data_saver')

    # ### end Alembic commands ###
