"""series external_ids

Revision ID: d59ac262ce53
Revises: b6a9fd5d186f
Create Date: 2026-07-25 04:13:40.586166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd59ac262ce53'
down_revision = 'b6a9fd5d186f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_ids_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_column('external_ids_json')

    # ### end Alembic commands ###
