"""initial schema

Revision ID: da574a33f5a8
Revises: 
Create Date: 2026-07-27 15:04:43.127668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da574a33f5a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('provider_list_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collection_provider_list_id'), ['provider_list_id'], unique=False)

    op.create_table('import_config',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=False),
    sa.Column('filename_pattern', sa.String(length=512), nullable=False),
    sa.Column('pattern_presets', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_scan_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('options_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('auto_match', sa.Boolean(), nullable=False),
    sa.Column('fetch_covers', sa.Boolean(), nullable=False),
    sa.Column('data_saver', sa.Boolean(), nullable=False),
    sa.Column('account_name', sa.String(length=128), nullable=True),
    sa.Column('client_id', sa.String(length=128), nullable=True),
    sa.Column('client_secret_enc', sa.Text(), nullable=True),
    sa.Column('refresh_token_enc', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_state',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_every_minutes', sa.Integer(), nullable=False),
    sa.Column('syncing', sa.Boolean(), nullable=False),
    sa.Column('new_chapters', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('group', sa.String(length=24), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tag_group'), ['group'], unique=False)

    op.create_table('tracker',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('sync_on_read', sa.Boolean(), nullable=False),
    sa.Column('account_name', sa.String(length=128), nullable=True),
    sa.Column('client_id', sa.String(length=128), nullable=True),
    sa.Column('client_secret_enc', sa.Text(), nullable=True),
    sa.Column('access_token_enc', sa.Text(), nullable=True),
    sa.Column('refresh_token_enc', sa.Text(), nullable=True),
    sa.Column('pkce_verifier', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=128), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series',
    sa.Column('library_id', sa.String(length=12), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('sort_title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('content_rating', sa.String(length=16), nullable=False),
    sa.Column('demographic', sa.String(length=16), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('origin_country', sa.String(length=2), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('user_rating', sa.Float(), nullable=True),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('library_status', sa.String(length=16), nullable=False),
    sa.Column('total_chapters', sa.Integer(), nullable=True),
    sa.Column('available_chapters', sa.Integer(), nullable=False),
    sa.Column('chapter_index_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('path_rel', sa.String(length=1024), nullable=True),
    sa.Column('cover_source', sa.String(length=1024), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('provider_series_id', sa.String(length=64), nullable=True),
    sa.Column('external_ids_json', sa.JSON(), nullable=True),
    sa.Column('image_count', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=512), nullable=True),
    sa.Column('characters_json', sa.JSON(), nullable=True),
    sa.Column('locked_fields_json', sa.JSON(), nullable=True),
    sa.Column('file_last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_series_content_rating'), ['content_rating'], unique=False)
        batch_op.create_index(batch_op.f('ix_series_demographic'), ['demographic'], unique=False)
        batch_op.create_index(batch_op.f('ix_series_favorite'), ['favorite'], unique=False)
        batch_op.create_index(batch_op.f('ix_series_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_series_library_id'), ['library_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_series_library_status'), ['library_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_series_sort_title'), ['sort_title'], unique=False)

    op.create_table('book',
    sa.Column('series_id', sa.String(length=12), nullable=False),
    sa.Column('library_id', sa.String(length=12), nullable=False),
    sa.Column('path_rel', sa.String(length=1024), nullable=False),
    sa.Column('content_kind', sa.String(length=16), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('partial_hash', sa.String(length=64), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('file_last_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('restore_progress_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_library_id'), ['library_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_series_id'), ['series_id'], unique=False)

    op.create_table('collection_series',
    sa.Column('collection_id', sa.String(length=12), nullable=False),
    sa.Column('series_id', sa.String(length=12), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'series_id')
    )
    op.create_table('provider_chapter',
    sa.Column('series_id', sa.String(length=12), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_chapter_id', sa.String(length=64), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=32), nullable=True),
    sa.Column('number_sort', sa.Float(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('group_name', sa.String(length=256), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'provider', 'provider_chapter_id', name='uq_provider_chapter_identity')
    )
    with op.batch_alter_table('provider_chapter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_chapter_number_sort'), ['number_sort'], unique=False)
        batch_op.create_index(batch_op.f('ix_provider_chapter_series_id'), ['series_id'], unique=False)

    op.create_table('series_credit',
    sa.Column('series_id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'name', 'role', name='uq_series_credit')
    )
    with op.batch_alter_table('series_credit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_series_credit_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_series_credit_series_id'), ['series_id'], unique=False)

    op.create_table('series_tag',
    sa.Column('series_id', sa.String(length=12), nullable=False),
    sa.Column('tag_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('series_id', 'tag_id')
    )
    op.create_table('title_variant',
    sa.Column('series_id', sa.String(length=12), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('variant_type', sa.String(length=16), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('title_variant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_title_variant_series_id'), ['series_id'], unique=False)

    op.create_table('chapter',
    sa.Column('series_id', sa.String(length=12), nullable=False),
    sa.Column('book_id', sa.String(length=12), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=32), nullable=True),
    sa.Column('number_sort', sa.Float(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('group_name', sa.String(length=256), nullable=True),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('source_uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('provider_chapter_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapter_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_number_sort'), ['number_sort'], unique=False)
        batch_op.create_index(batch_op.f('ix_chapter_series_id'), ['series_id'], unique=False)

    op.create_table('download_task',
    sa.Column('series_id', sa.String(length=12), nullable=False),
    sa.Column('chapter_id', sa.String(length=12), nullable=True),
    sa.Column('chapter_label', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=16), nullable=True),
    sa.Column('detail', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('remote_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('download_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_download_task_series_id'), ['series_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_download_task_status'), ['status'], unique=False)

    op.create_table('reading_progress',
    sa.Column('chapter_id', sa.String(length=12), nullable=False),
    sa.Column('series_id', sa.String(length=12), nullable=False),
    sa.Column('current_page', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reading_progress_chapter_id'), ['chapter_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_reading_progress_series_id'), ['series_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reading_progress_series_id'))
        batch_op.drop_index(batch_op.f('ix_reading_progress_chapter_id'))

    op.drop_table('reading_progress')
    with op.batch_alter_table('download_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_download_task_status'))
        batch_op.drop_index(batch_op.f('ix_download_task_series_id'))

    op.drop_table('download_task')
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter_series_id'))
        batch_op.drop_index(batch_op.f('ix_chapter_number_sort'))
        batch_op.drop_index(batch_op.f('ix_chapter_book_id'))

    op.drop_table('chapter')
    with op.batch_alter_table('title_variant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_title_variant_series_id'))

    op.drop_table('title_variant')
    op.drop_table('series_tag')
    with op.batch_alter_table('series_credit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_credit_series_id'))
        batch_op.drop_index(batch_op.f('ix_series_credit_name'))

    op.drop_table('series_credit')
    with op.batch_alter_table('provider_chapter', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_chapter_series_id'))
        batch_op.drop_index(batch_op.f('ix_provider_chapter_number_sort'))

    op.drop_table('provider_chapter')
    op.drop_table('collection_series')
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_series_id'))
        batch_op.drop_index(batch_op.f('ix_book_library_id'))

    op.drop_table('book')
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_sort_title'))
        batch_op.drop_index(batch_op.f('ix_series_library_status'))
        batch_op.drop_index(batch_op.f('ix_series_library_id'))
        batch_op.drop_index(batch_op.f('ix_series_kind'))
        batch_op.drop_index(batch_op.f('ix_series_favorite'))
        batch_op.drop_index(batch_op.f('ix_series_demographic'))
        batch_op.drop_index(batch_op.f('ix_series_content_rating'))

    op.drop_table('series')
    op.drop_table('tracker')
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_group'))

    op.drop_table('tag')
    op.drop_table('sync_state')
    op.drop_table('provider')
    op.drop_table('library')
    op.drop_table('import_config')
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collection_provider_list_id'))

    op.drop_table('collection')
    # ### end Alembic commands ###
