"""add tracker connect-state nonce

Revision ID: e54a78664e3e
Revises: 44d2dfce9ddb
Create Date: 2026-07-27 12:58:29.240227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e54a78664e3e'
down_revision = '44d2dfce9ddb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracker', schema=None) as batch_op:
        batch_op.drop_column('state')

    # ### end Alembic commands ###
